//SPDX-License-Identifier: Unlicense
// DO NOT EDIT THIS FILE
pragma solidity ^0.8.0;

import "hardhat/console.sol";
import '@openzeppelin/contracts/token/ERC20/ERC20.sol';

interface ICurve{
    function exchange(int128, int128, uint256, uint256) external;
}

contract Depeg{
    address pool = 0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7;
    address usdc = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    uint256 MAX_INT = 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff;

    function messWithPeg() external {
        uint256 usdcBalance = ERC20(usdc).balanceOf(address(this));
        ERC20(usdc).approve(pool, usdcBalance);
        ICurve(pool).exchange(int128(1), int128(0), usdcBalance, 0);
    }
}